<?php

namespace Jihan\JunitLaravel\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Route;

/**
 *
 *
 * 组件传统范式应用的话，
 * Class JunitServiceProvider
 * @package Jihan\JunitLaravel\Providers
 */

class JunitServiceProvider extends ServiceProvider
{
//
//    public function register()
//    {
//        parent::register(); // TODO: Change the autogenerated stub
//    }

    public function boot()
    {

        $this->registerRoutes();

        $this->loadViewsFrom(
            __DIR__.'/../resources/views', 'junit'
        );

    }


    public function routeConfiguration()
    {
        return [
            'namespace' => 'Jihan\JunitLaravel\Http\Controllers',
            'prefix' => 'junit'
        ];
    }

    private function registerRoutes()
    {
//        dd(__DIR__.'/../');
        Route::group($this->routeConfiguration(), function (){
            $this->loadRoutesFrom(__DIR__."/../Http/routes.php");
        });

    }


}

?>